main.tf, test/integration/default/local_alb.rb
This PR fixes `~ module.alb.aws_s3_bucket.log_bucket` which happens every time I run plan.
=> Fixed S3 bucket policy to make it canonical

outputs.tf
This is useful if you plan to use ALB with ECS. 
I'm using ECS to host my apps and ALB is in front. When using aws_alb_listener_rule for path-based routing it requires alb_listener_arn.
I'm not sure if it is possible to export only HTTP or HTTPS based on which one is actually used?
=> Alb listener outputs

outputs.tf
With v0.11 Terraform now checks outputs for errors so as not to propagate them through modules etc and help in debugging. This seems to fix the error when using only HTTP or HTTPS listener.
More here (near the bottom):
https://www.terraform.io/upgrade-guides/0-11.html
=> Possible fix for Terraform v0.11(output to non-existing resource)

outputs.tf
In some cases, it can be desirable to have access to the ALB ARN. One example of this is if you want to attach a WAF to it.
=> Add ARN of ALB to outputs

main.tf, test/integration/default/local_alb.rb, variables.tf
I'm using ALB as a front for Jenkins and usually it responds 403 on / so having a possiblity to change the expected HTTP code seems fine.
=> Adding the health check code for ALB health checking

.kitchen.yml, .travis.yml, CHANGELOG.md, Gemfile, examples/test_fixtures/main.tf, main.tf, test/integration/default/local_alb.rb, variables.tf
This change contains:
* much comment clean up
* adapting travis ci code to kitchen terraform 3 (currently pulling from branch)
* renaming the `health_check_code` to `health_check_matcher` (more closely resembles terraform code)
=> move to kitchen-terraform 3.0.x and terraform 0.11.0

Gemfile, main.tf, variables.tf
On three occasions when using this module the S3 bucket was either created after the ALB, or wasn't ready by the time the ALB was trying to set up access logs and I received errors like this:
```
aws_alb.main: Failure configuring ALB attributes: ValidationError: S3Bucket: bucket_name does not exist
status code: 400, request id: xxxxx-xxxxxx-xxxxxx-xxxxxx-xxxxxx
```
If the option to have the module create the bucket is selected, this ensures the bucket is created before trying to tell the ALB to send logs there.
I tested this with both `create_log_bucket` set to `true` and `false` and it worked both ways. Additionally I ran the `kitchen test` and here is the tail end of the output (it was succesful)
```
Destroy complete! Resources: 24 destroyed.
$$$$$$ Running command `terraform workspace …
```
=> Create bucket before provisioning access logs on the ALB

main.tf, variables.tf
Add ALB target group target_type variable and  depends_on to alb relate resource.
=> Add  target group target_type variable and  depends_on

variables.tf
Re: using `force_destroy_log_bucket` - and the `force_destroy` keyword - on `aws_s3_bucket`. This doesn't destroy and recreate the buckets, it just (on destroy) recursively deletes objects in the buckets and cleanly deletes the bucket without error.  The description is misleading, so I've simply put the [upstream resource's description](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html) in here.
=> update force_destroy_log_bucket description

outputs.tf
In order to use the target group with a [codedeploy_deployment_group](https://www.terraform.io/docs/providers/aws/r/codedeploy_deployment_group.html) we need to use the name of the target group instead of it's arn.
=> Add target_group.name to outputs.tf

data.tf
When omitting the log_location_prefix, the generated policy is left with an extraneous `/` in the resource.  By default (without a location prefix) the ALB will write to the bucket root, so the created policy will not allow that access.  This adds a slash if a prefix is specified and otherwise omits one.
=> Omitting log_location_prefix creates an invalid bucket policy

examples/alb_test_fixture/main.tf, main.tf
This PR addresses the issue raised in #52.
* Uses `name = ` instead of `name_prefix = ` for the ALB name
* Eliminates forced use of `name_prefix`
* Uses a `random_id` hex value for the test fixture to avoid naming conflict in lieu of `name_prefix` (which appears to have been the motivation behind the change in the first place based on `v3.0.0` CHANGELOG)
=> Fix `name_prefix` limiting ALB name descriptiveness to 6 characters

main.tf
When modifying default tg the new one need to be created for listener be able to use it and terraform can destroy the old one later
=> This fixes #57

outputs.tf
This is helpful in adding cloud watch monitor(s) for a given number of healthy instances:
From the module invocation, where we specify the list of target groups:
`target_groups = "${list
(map
("name", "${var.app1}", "backend_protocol", "HTTP", "backend_port", "8080"
),
(map
("name", "${var.app2}", "backend_protocol", "HTTP", "backend_port", "80"
)
)
)}"`
Cloudwatch usage:
`resource "aws_cloudwatch_metric_alarm" "app1_unhealthy_hosts" {
alarm_name          = "${var.app1}-unhealthy-host"
comparison_operator = "LessThanThreshold"
datapoints_to_alarm = "3"
evaluation_periods  = "5"
metric_name         = "HealthyHostCount"
namespace           = "AWS/ApplicationELB"
period              = "60"
statistic           = "Maximum"
threshold           = "2"
dimensions {
TargetGroup   = …
=> add target_group_arn_suffixes output

.pre-commit-config.yaml, README.md, examples/alb_test_fixture/README.md
@brandoconnor I am adding the same autogenerated documentation using pre-commit hooks to all terraform-aws-modules.
Feel free to adjust it if you want.
=> Added pre-commit hook to autogenerate terraform-docs

README.md, alb_no_logs.tf, alb_w_logs.tf, variables.tf
I added a new variable to support enabling cross zone load balancing.
The [argument of `aws_lb` resource](https://www.terraform.io/docs/providers/aws/r/lb.html#enable_cross_zone_load_balancing) is called `enable_cross_zone_load_balancing` and is `false` by default so I do the same thing in the module.
I tested this within our own running AWS environment and it seems to work properly.
The test set that was documented (ie. `bundle exec kitchen test`) somehow didn't work for me.
I ran the test using a docker container with ruby as follow:
```bash
docker run -it --rm -v $PWD:/source -w /source --env-file=$HOME/.aws/tf_test_env -v $HOME/Downloads/linux-terraform:/bin/terraform --entrypoint bash ruby:2.4.2
root@327539cefb64:/source# gem install bundler && bundle install
Fetching: …
```
=> Add variable to support setting cross-zone-load-balancing

.travis.yml
Fixing the failing build as a result of an option for tflint as it was both set as the default and removed as an option.
https://travis-ci.org/terraform-aws-modules/terraform-aws-alb
=> Remove --error-with-issues option on tflint as it is now default and removed

alb_no_logs.tf, alb_w_logs.tf
When you specify two ALB listeners (http-80 and http-8080) and two Target Groups (tg-80 and tg-8080), you get the following mapping:
```
http-80 -> tg-80
http-8080 -> tg-80
```
and instead of the expected:
```
http-80 -> tg-80
http-8080 -> tg-8080
```
https://github.com/terraform-aws-modules/terraform-aws-alb/issues/119
=> Set correct TG for listeners (fixed #119)

alb_no_logs.tf, alb_w_logs.tf
When you specify two ALB listeners (http-80 and http-8080) and two Target Groups (tg-80 and tg-8080), you get the following mapping:
```
http-80 -> tg-80
http-8080 -> tg-80
```
and instead of the expected:
```
http-80 -> tg-80
http-8080 -> tg-8080
```
Please explain the changes you made here and link to any relevant issues.
=> Set correct TG for listeners for Terraform 0.11 (fixed #119)

README.md
Fixed the hyperlink for 'Target Group Attachement'. It linked to the lb_listener_rule.
Please explain the changes you made here and link to any relevant issues.
=> Fixed hyperlink in README.md

variables.tf
Removed an old leftover input variable no longer used.
For backwards compatibility it could instead be used for "prefix" in access_logs variable, but personally I think that would just make it more confusing.
* [-] Tests for the changes have been added and passing (for bug fixes/features)
* [-] Test results are pasted in this PR (in lieu of CI)
* [- Not mentioned in docs] Docs have been added/updated (for bug fixes/features)
* [v] Any breaking changes are noted in the description above
=> Removed unused (depracated) input variable

main.tf, variables.tf, versions.tf
Allow to enable drop_invalid_header_fields on application load balancer
Now, it is possible to drop invalid headers if they are invalid on ALB
Allow this AWS feature
NA
I use this version and check option in the AWS console
=> feat: Add support for drop_invalid_header_fields

README.md, examples/complete-alb/main.tf, examples/complete-nlb/main.tf, main.tf, variables.tf
This PR will allow this module to add tags on : 
* load balancer only
* all taget groups
* specific target group
Sometimes, we want to add tags only in a specific resource, and not to all resources. Example, a target group description tag like "use for admin acess". 
Nothing. 
Make a terraform plan on tests
```
terraform plan -out /tmp/plan.out examples/complete-alb
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
data.aws_route53_zone.this: Refreshing state...
data.aws_vpc.default: Refreshing state...
data.aws_subnet_ids.all: Refreshing state...
------------------------------------------------------------------------
An execution plan has been generated and is shown …
```
=> feat: Add more specific tags

README.md, variables.tf
…ME.md to adjust to the 6 character limit that the value can take. Fixes issue #161
Updated description and examples of name_prefix argument in README.md to adjust to the 6 character limit that the value can take. 
Related to issue https://github.com/terraform-aws-modules/terraform-aws-alb/issues/161
No
No testing other than looking at the modified file as this is an update in the README.md
=> docs: Updated description and examples of name_prefix argument

README.md, versions.tf
Fixes #165
Support AWS provider 3.0 by allowing any version greater than 2.54
Per Terraform documentation, pessimistic version constraints should not be used for providers
https://www.terraform.io/docs/configuration/provider-requirements.html#best-practices-for-provider-versions
See AWS provider [documentation](https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v3.0.0)
None yet.
=> feat: Support AWS provider 3.0 and Terraform 0.13

CHANGELOG.md
Add optional arguments to target group:  `load_balancing_algorithm_type`
https://www.terraform.io/docs/providers/aws/r/lb_target_group.html#load_balancing_algorithm_type
Closes #157 
No breaking changes
Created Load balancer with `load_balancing_algorithm_type` set to `least_outstanding_requests`, `round_robin`, and unset. All load balancers' target group created as it should be.
=> feat: Support Least Outstanding Requests algorithm for load balancing requests

README.md, examples/complete-alb/main.tf, main.tf, variables.tf
Added listener rules support.
This PR adds support for creating `aws_lb_listener_rule` resources, with all currently supported actions and conditions from the terraform provider supported. For now, I only added support to https listeners, but adding http listener support later would be trivial.
Docs wise, I updated the REAMDE to include an example of using the listener_rule var, and also updated the example to have near-complete usage.
This repo recently added support for updating the default rule for a listener, which was awesome. This PR goes one step further, for adding rules with conditions, such as only protecting certain paths with authentication.
Fixes: https://github.com/terraform-aws-modules/terraform-aws-alb/issues/154
There are no breaking changes. Plans will be empty on …
=> feat: Added listener rules support

.gitignore, .pre-commit-config.yaml, README.md, examples/complete-alb/README.md, examples/complete-nlb/README.md
- update documentation based on latest `terraform-docs` which includes module and resource sections
- `.gitignore` updated using GitHub provided default standard + 0.14 lockfile ignore
- these are two new sections provided by [`terraform-docs` now](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.11.0)
No
N/A
=> chore: update documentation based on latest `terraform-docs` which includes module and resource sections

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, examples/complete-alb/README.md, examples/complete-alb/versions.tf, examples/complete-nlb/README.md, examples/complete-nlb/versions.tf
- align ci-cd static checks to use individual minimum Terraform versions
- ensure that the modules are all following a similar workflow and the static checks that performed
- No
- ci-cd static checks
=> chore: align ci-cd static checks to use individual minimum Terraform versions

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, README.md, examples/complete-alb/README.md, examples/complete-nlb/README.md
- update documentation and pin `terraform_docs` version to avoid future changes
- pin version to avoid unnecessary updates when a PR coincides with a version update for `terraform_docs`
- no
- documentation change only - ci/cd should pass checks
=> chore: update documentation and pin `terraform_docs` version to avoid future changes

README.md
Update the readme with new github issue and terraform/aws provider versions that contain the issue.
The previous link was closed, suggesting it was fixed, however the problem still persists in the newest versions of terraform (v0.14.8) and the aws provider (v3.33.0).
None 
Can confirm that this is still an issue by uncommenting the commented out `log_bucket` module and `access_logs` in the alb example.
=> chore: Update readme note on S3 access logs bucket creation

.github/workflows/pre-commit.yml, .gitignore, README.md, examples/complete-alb/README.md, examples/complete-alb/main.tf, examples/complete-alb/outputs.tf, examples/complete-alb/versions.tf, examples/complete-nlb/README.md, examples/complete-nlb/versions.tf, main.tf, outputs.tf, versions.tf
Allows for the creation of a "targets" index inside the target_groups variable, where the parameters of the attachment can be defined. The same arguments that are used for the target_group_attachment resource, are the same arguments that should/can be defined. Any additional arguments are created during the "product mapping", but are not used in the resource, but allows for easy upgrading in the future if more arguments are added (only have to update on the resource function)
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group_attachment#argument-reference
Allow attaching EC2 instance(s) and Lambda functions to the target groups created by this module so all resources can be managed in one location.  Currently, there's no functionality to add any …
=> feat: Add target group attachment capabilities

main.tf
=> fix: Empty target group attachments for Terraform 0.13

README.md, examples/complete-alb/README.md, examples/complete-alb/main.tf, examples/complete-alb/versions.tf, examples/complete-nlb/README.md, examples/complete-nlb/versions.tf, main.tf, versions.tf
This pull request adds support for the [`protocol_version`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group#protocol_version) argument of the `aws_lb_target_group` resource.
Resolves #179
hashicorp/terraform-provider-aws#17534
N/A
=> feat: support for target group protocol_version

CHANGELOG.md, main.tf
I have a project on my company where we needed to be able to set ALPN policies for the target group attachments since we support some legacy apps. I added the Ability to add that value inside the map that you send to the module:
```
{
action_type        = "forward"
port               = 443
protocol           = "TLS"
target_group_index = 2
certificate_arn    = "arn:aws:acm:us-west-2:1234567890:certificate/b123456789...."
alpn_policy        = "HTTP2Optional"
}
```
It adds capacity to map ALPN policies to target groups.
- I tested this change in my enviornment and it is working as expected using NLB's.
The plan now outputs to this when the alpn_policy is set:
```
https_listeners = [
{
action_type        = "forward"
port               = 443
protocol           = "TLS"
target_group_index = 2 …
```
=> feat: Adding support for ALPN policies

main.tf
It has been introduced in this PR but I do not see any reason for it. A target group can be created without a lb.
https://github.com/terraform-aws-modules/terraform-aws-alb/pull/37/
In the following PR, some depends_on have been removed but not this one:
https://github.com/terraform-aws-modules/terraform-aws-alb/pull/49
=> fix: Remove not required depends_on in aws_lb_target_group

examples/complete-alb/main.tf, main.tf, variables.tf
Added a 'weighted-forward' dynamic action block to use with the https_listener_rules for multiple weighted target_group
This adds a dynamic action block for a "weighted-forward" action_rule.type for the https_listener_rules . It allows us to create a listener rule like: 
```
{
https_listener_index = 0
priority             = 30
actions = [
{
type = "weighted-forward"
target_groups = [
{
target_group_index = 1
weight             = 1
},
{
target_group_index = 0
weight             = 0
}
]
}
]
conditions = [{}]
}
```
Fixes #211 
No breaking changes
- [√] I have tested and validated these changes using one or more of the provided `examples/*` projects
I created the resources and visually verified the correct rules made it onto the load balancer.
```
+ forward {
+ stickiness {
+ duration = 0
+ …
```
=> feat: Support weight in forward action

README.md, main.tf, variables.tf, versions.tf
Resource aws_lb support enable_waf_fail_open and desync_mitigation_mode, support for which is missing in this module.
I have added support for these options in current aws_lb resource implementation.
Also added the variables for these 2 options.
In some cases, it is needed to set **enable_waf_fail_open** to true, as for supporting critical services, sometimes it impact customers with the communication to aws waf fails.
Does this break backwards compatibility with the current major version?
No
If so, please provide an explanation why it is necessary.
NA
=> feat: Add support for enable_waf_fail_open and desync_mitigation_mode

.pre-commit-config.yaml, README.md, examples/complete-alb/README.md, examples/complete-alb/main.tf, examples/complete-nlb/README.md, examples/complete-nlb/main.tf, main.tf
This PR add 'weighted-forward' dynamic action block to use with the _http_tcp_listener_rule_ for multiple weighted target_group.
It is very close to #224 but manage the http.
This adds a dynamic action block for a "weighted-forward" action_rule.type for the http_tcp_listener_rules . It allows us to create a listener rule like:
```
{
http_tcp_listener_index = 0
priority                = 30
actions = [
{
type = "weighted-forward"
target_groups = [
{
target_group_index = 1
weight             = 1
},
{
target_group_index = 0
weight             = 0
}
]
}
]
conditions = [{}]
}
```
No breaking changes
I created the resources and visually verified the correct rules made it onto the load balancer.
```
+ forward {
+ stickiness {
+ duration = 0
+ enabled  = false
}
+ target_group {
+ arn    = …
```
=> feat: Added `weighted-forward` rules for HTTP

main.tf
Adding optional `cookie_name` parameter support for the target group stickiness. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group#cookie_name
We have got an issue while trying to provision ALB with TG stickiness type `app_cookie` due to a lack of `cookie_name` parameter support.
Fixes #242
We are not aware of breaking changes. Changes should be backward compatible(one optional parameter support added)
- We have tested changes by creating TGs with stickiness types `lb_cookie` and `app_cookie`
=> feat: Added missing `cookie_name` TG stickiness parameter support

.pre-commit-config.yaml, README.md, examples/complete-alb/README.md, examples/complete-alb/main.tf, main.tf
This PR adds the `aws_lambda_permission` resource that should be created before the `aws_lb_target_group_attachment` is created.
`target_groups.targets` is extended to allow `aws_lambda_permission` attributes to be passed in. The new attributes are listed under the top level of `target_groups.target` which makes the structure very flat. The ideal case would nest those within a `target_groups.target.lambda_permissions` however this is not possible as it leads to this problem [https://github.com/hashicorp/terraform/issues/22405](https://github.com/hashicorp/terraform/issues/22405)
The trigger on the lambda resource is also removed from the complete example as it is unnecessary now
The problem was that the lambda ARN is an input to the module. However, to create the permissions for the …
=> feat: Added support for lambda permissions when the target is a lambda function

README.md, examples/complete-alb/README.md, examples/complete-alb/versions.tf, examples/complete-nlb/README.md, examples/complete-nlb/versions.tf, main.tf, versions.tf
Adds the ip_address_type resource to the aws_lb_target_group resource so you can specify ipv6 targets.
I have a need to create an ipv6 only target group, and the module didn't currently have that ability while AWS did.
=> feat!: Add ip_address_type to target group resource, bumped AWS provider version

examples/complete-nlb/main.tf
Added stickiness in complete-nlb example
Stickiness was missing in the example and hence would take some time for other users to be able to use it
on this module.
No breaking changes as modification was done in examples/ only
=> docs: Added stickiness to examples and README

main.tf
Changes the order of `merge()` on the tags to allow override of the `Name` tag.
I prefer to use `name_prefix` when creating load balancers. This ensures all the load balancers are created with unique names. However, it becomes difficult to determine which load balancer I am viewing in the AWS console because they are start with the same prefix. The only way to see which one I am looking at is to review the rules. 
My solution is to use a `Name` tag passed into the variable `lb_tags`. This module currently overrides any `Name` tag I pass with the value of `name_prefix`. By changing the order of the `merge()` on the tags, the module can still set `Name` if it is not passed in, but won't override it if it is.
This PR is loosely related to #52.
There is no breaking changes in this PR.
I …
=> fix: Allow for override of Name tag on load balancer

.pre-commit-config.yaml, README.md, examples/complete-alb/README.md, examples/complete-alb/main.tf, examples/complete-alb/outputs.tf, examples/complete-alb/versions.tf, main.tf, outputs.tf, variables.tf, wrappers/main.tf
- Add support for creating a security group along with the load balancer
- All ALBs created require a security group which then means another module definition for users. Instead, this now adds the ability to add the necessary rules directly into the ALB module. In the future, I'd like to look at mapping the listeners into rules to where users only need to specify the port and protocol once and this will create the necessary network access (they will still have to add CIDR blocks, etc., to know where that traffic is coming from or going to, but the port and protocol won't be duplicated)
- No
=> feat: Add support for creating a security group along with the load balancer

examples/complete-alb/README.md, examples/complete-alb/main.tf, examples/complete-alb/variables.tf, examples/complete-nlb/README.md, examples/complete-nlb/main.tf, examples/complete-nlb/variables.tf, examples/complete-nlb/versions.tf, main.tf
- Correct stickiness syntax and ensure that security group is not created for network load balancers
- Update examples to allow other users to test with a domain and align example usage
- Resolves #276 
- Resolves #275 
- No
=> fix: Correct stickiness syntax and ensure that security group is not created for network load balancers

examples/complete-alb/main.tf, main.tf
feat: default-action forward action type
AWS Code Deploy Blue/Green Deployment automatically register 2 target group for 1 application. The first one is blue target group, and the other is green target group.
No.
```
http_tcp_listeners = [
{
port     = 80
protocol = "HTTP"
action_type = "forward"
forward = {
target_groups = [
{
target_group_index = 0
weight             = 100
},
{
target_group_index = 1
weight             = 0
}
]
}
}
]
```
=> feat: Default action forward action type

main.tf
Add comment explaining 6th index after split function in lambda_function_name value.
Lambda function ARN format is not specified in the comments so it is quite confusing why 6th index is taken as the lambda_function_name value
This does not have breaking changes and is backward compatible. Only comments are added.
=> docs: Add lambda_function_arn format for lambda_function_name

README.md, docs/patterns.md
Adding patterns for common patterns usage
Related: [Request for contributions - Usage patterns](https://github.com/terraform-aws-modules/terraform-aws-alb/issues/311)
No breaking changes
=> docs: Adding patterns for common usage

README.md, examples/complete-alb/README.md, examples/complete-alb/versions.tf, examples/complete-nlb/README.md, examples/complete-nlb/main.tf, examples/complete-nlb/versions.tf, main.tf, variables.tf, versions.tf, wrappers/main.tf
Add `dns_record_client_routing_policy` to `aws_lb` and `target_health_state` to `aws_lb_target_group`.
https://github.com/hashicorp/terraform-provider-aws/pull/34070
https://github.com/hashicorp/terraform-provider-aws/issues/33992
No.
=> feat: Add support for disabling connection termination for unhealthy targets and AZ DNS affinity

docs/patterns.md
- Add usage patterns for authenticated listeners from Atlantis module docs
- These are defined in the [Atlantis module documentation](https://github.com/terraform-aws-modules/terraform-aws-atlantis#secure-atlantis-with-alb-built-in-authentication) but they aren't specific to Atlantis and would make a great addition to the usage patterns docs here
- Relates to #311
- No
=> docs: Add usage patterns for authenticated listeners from Atlantis module docs

README.md, UPGRADE-9.0.md, docs/patterns.md, examples/complete-alb/main.tf
Fixing some examples in the documentation. Correct key names for protocol and port in target groups.
The documentation is wrong and may cause confusion when upgrading to version 9.
It's easy to miss this because the examples silently fall back on defaults.
I suppose some type of validation could catch this earlier.
No.
=> docs: Correct key names for protocol and port in target groups

main.tf
Add ```ignore_changes``` to ```aws_lb```.
To avoid this situation when we have a shared ALB with ElasticBeanstalk
```  # module.alb.aws_lb.this[0] will be updated in-place
~ resource "aws_lb" "this" {
id                                          = "arn:aws:elasticloadbalancing:xxx:xxxx:loadbalancer/app/shared-alb/xxx"
name                                        = "shared-alb"
~ tags                                        = {
- "elasticbeanstalk:shared-elb-environment-count" = "1" -> null
"terraform-aws-modules"                         = "alb"
}
~ tags_all                                    = {
- "elasticbeanstalk:shared-elb-environment-count" = "1" -> null
}
}```
```
No.
=> feat: Add ignore changes on tags to `elasticbeanstalk:shared-elb-environment-count`

examples/README.md
Just add a link from [/examples/README.md](https://github.com/terraform-aws-modules/terraform-aws-alb/tree/master/examples/README.md) to [/docs/patterns.md](https://github.com/terraform-aws-modules/terraform-aws-alb/tree/master/docs/patterns.md).
For ease of finding relevant code snippets, spanning multiple documentation pages.
No.
Tangentially relates to #311.
=> docs: Link from examples to patterns

docs/patterns.md
Per #311, adding a new usage pattern enabling multiple target groups to be provisioned using a for loop.
By leveraging a for loop with maps, it enables provisioning-at-scale and keep code DRY.
No.
=> docs: Add multiple target groups with for loop pattern

README.md, variables.tf, wrappers/main.tf
Change default of `subnets` from `[]` to `null`.
Fix #340.
No. As far as I know, the previous default of `subnets = []` is useless, because
- the default will be overridden when `subnets` is provided by user, or
- the default will be ignored when `subnet_mapping` is provided by user.
- No change to examples were needed.
- Tested with the code in #340.
=> fix: Change `subnets` default value to `null`

.gitignore, README.md, examples/complete-alb/README.md, examples/complete-alb/versions.tf, examples/complete-nlb/README.md, examples/complete-nlb/versions.tf, examples/mutual-auth-alb/README.md, examples/mutual-auth-alb/ca.conf, examples/mutual-auth-alb/main.tf, examples/mutual-auth-alb/outputs.tf, examples/mutual-auth-alb/variables.tf, examples/mutual-auth-alb/versions.tf, main.tf, modules/lb_trust_store/README.md, modules/lb_trust_store/main.tf, modules/lb_trust_store/outputs.tf, modules/lb_trust_store/variables.tf, modules/lb_trust_store/versions.tf, versions.tf, wrappers/lb_trust_store/README.md, wrappers/lb_trust_store/main.tf, wrappers/lb_trust_store/outputs.tf, wrappers/lb_trust_store/variables.tf, wrappers/lb_trust_store/versions.tf
Closes: https://github.com/terraform-aws-modules/terraform-aws-alb/issues/342
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/mutual-authentication.html
https://aws.amazon.com/blogs/aws/mutual-authentication-for-application-load-balancer-to-reliably-verify-certificate-based-client-identities/
https://github.com/terraform-aws-modules/terraform-aws-alb/issues/342
No.
=> feat: Added support for ALB trust store

.pre-commit-config.yaml, README.md, UPGRADE-5.0.md, examples/complete-alb/README.md, examples/complete-alb/main.tf, main.tf, variables.tf, wrappers/main.tf
This adds a variable `additional_target_group_attachments` for specifying additional attachments for target groups.
This is particularly useful when the only handle you have to an instance is its IP address, and you need to provide multiple IPs to a target group.
Resolves #316
This does not break backwards compatibility.
- I deployed the examples/complete-alb without my changes, and then with my changes. The target group `ex-instance` successfully deploys with an additional target, `aws_instance.other`
=> feat: Additional target group attachments

README.md
Add missing `target_id` to examples on README.md
When running the sample example the attribute is missing.
Closes https://github.com/terraform-aws-modules/terraform-aws-alb/issues/364
=> docs: Add missing target id to docs

README.md, examples/complete-alb/README.md, examples/complete-alb/main.tf, examples/complete-alb/versions.tf, examples/complete-nlb/README.md, examples/complete-nlb/versions.tf, examples/mutual-auth-alb/README.md, examples/mutual-auth-alb/versions.tf, main.tf, modules/lb_trust_store/README.md, modules/lb_trust_store/versions.tf, versions.tf
Add support for `target_group_health` block.
Added random string to `aws_cognito_user_pool_domain` `domain` since they must be unique across all accounts and regions otherwise `Domain already associated with another user pool.` error is provided. 
https://github.com/hashicorp/terraform-provider-aws/pull/37082
No.
=> feat: Add `target_group_health` block

.github/workflows/pr-title.yml, .github/workflows/pre-commit.yml, .pre-commit-config.yaml, README.md, examples/complete-alb/README.md, examples/complete-nlb/README.md, examples/mutual-auth-alb/README.md, modules/lb_trust_store/README.md, wrappers/lb_trust_store/versions.tf, wrappers/versions.tf
- Update CI workflow versions to latest
- Updates our workflows to use the latest versions
- Removes warnings for Python 3.12 in runners
- No
=> fix: Update CI workflow versions to latest

examples/complete-alb/main.tf, main.tf
Fix to allow you to pass multiple query string to load balancer rule
We needed to add 2 conditions as an OR statement are the current module did not support it
No
=> fix: To allow multiple query strings as an OR statement

README.md, examples/complete-alb/README.md, examples/complete-alb/versions.tf, examples/complete-nlb/README.md, examples/complete-nlb/main.tf, examples/complete-nlb/versions.tf, examples/mutual-auth-alb/README.md, examples/mutual-auth-alb/versions.tf, main.tf, modules/lb_trust_store/README.md, modules/lb_trust_store/versions.tf, variables.tf, versions.tf, wrappers/lb_trust_store/versions.tf, wrappers/main.tf, wrappers/versions.tf
Support `aws_lb.enable_zonal_shift` and `aws_lb_listener.tcp_idle_timeout_seconds`.
https://github.com/hashicorp/terraform-provider-aws/pull/39585
No.
=> feat: Support `aws_lb.enable_zonal_shift` and `aws_lb_listener.tcp_idle_timeout_seconds`

README.md, examples/complete-alb/README.md, examples/complete-alb/versions.tf, examples/complete-nlb/README.md, examples/complete-nlb/versions.tf, examples/mutual-auth-alb/README.md, examples/mutual-auth-alb/versions.tf, main.tf, modules/lb_trust_store/README.md, modules/lb_trust_store/versions.tf, versions.tf, wrappers/lb_trust_store/versions.tf, wrappers/versions.tf
Support `aws_lb_listener.mutual_authentication.advertise_trust_store_ca_names`.
https://github.com/hashicorp/terraform-provider-aws/pull/40550
No.
=> feat: Support `aws_lb_listener.mutual_authentication.advertise_trust_store_ca_names`

.pre-commit-config.yaml, examples/complete-alb/main.tf
The complete-alb example needs a few fixes to apply without errors.
`terraform apply` returns a warning and some errors:
```
╷
│ Warning: Invalid Attribute Combination
│ 
│   with module.alb.aws_lb_target_group.this["ex-lambda-with-trigger"],
│   on ../../main.tf line 578, in resource "aws_lb_target_group" "this":
│  578:   port                               = each.value.target_type == "lambda" ? null : coalesce(each.value.port, var.default_port)
│ 
│ Attribute "port" cannot be specified when "target_type" is "lambda".
│ 
│ This will be an error in a future release.
│ 
│ (and one more similar warning elsewhere)
╵
╷
│ Error: Missing required argument
│ 
│   with module.alb.aws_lb_listener_rule.this["ex-http-https-redirect/ex-weighted-forward"],
│   on ../../main.tf line 299, in resource …
```
=> docs: Update the complete-alb example to apply without errors
